-- FUNÇÕES DE STRING

SELECT NOME,UPPER (NOME),LOWER(NOME) FROM TABELA_DE_CLIENTES;

SELECT NOME_DO_PRODUTO, INITCAP(NOME_DO_PRODUTO) FROM TABELA_DE_PRODUTOS;

-- FORMAS DE USAR O C0NCAT

SELECT ENDERECO_1,BAIRRO,CONCAT(ENDERECO_1,BAIRRO) FROM TABELA_DE_CLIENTES;

SELECT ENDERECO_1, BAIRRO, CONCAT(CONCAT(ENDERECO_1,' '),BAIRRO)FROM TABELA_DE_CLIENTES;

SELECT ENDERECO_1||' '||BAIRRO||' '||CIDADE||' '||ESTADO|| '-'||CEP FROM TABELA_DE_CLIENTES;

---------------------------

SELECT NOME_DO_PRODUTO,LPAD(NOME_DO_PRODUTO,70,'!') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO,RPAD(NOME_DO_PRODUTO,70,'!') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO ,SUBSTR(NOME_DO_PRODUTO,3,5) FROM TABELA_DE_PRODUTOS;

SELECT NOME,INSTR(NOME,'Silva')FROM TABELA_DE_CLIENTES;

SELECT NOME FROM TABELA_DE_CLIENTES WHERE  INSTR (NOME,'Silva')<>0; 

SELECT '   VICTORIANO    ',LTRIM('   VICTORIANO    ')AS X FROM DUAL;

SELECT '   VICTORIANO    ',RTRIM('   VICTORIANO  ')AS Y FROM DUAL;

SELECT '   VICTORIANO    ',TRIM('   VICTORIANO  ')AS Z FROM DUAL;

SELECT NOME_DO_PRODUTO, REPLACE(NOME_DO_PRODUTO,'Litro','L') FROM TABELA_DE_PRODUTOS;

SELECT NOME_DO_PRODUTO, REPLACE(REPLACE(NOME_DO_PRODUTO,'Litro','L'),'Ls','L') FROM TABELA_DE_PRODUTOS;

---------------------------

-- FUNÇÕES DE DATA

SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE,'DD,MM,YYYY HH:MI:SS') FROM DUAL;

SELECT NOME,DATA_DE_NASCIMENTO FROM TABELA_DE_CLIENTES;

SELECT NOME,TO_CHAR(DATA_DE_NASCIMENTO,'DD MONTH YYYY DAY' ) FROM TABELA_DE_CLIENTES;

SELECT SYSDATE + 127 FROM DUAL;

SELECT NOME,IDADE, (SYSDATE - DATA_DE_NASCIMENTO)/365 FROM TABELA_DE_CLIENTES;

SELECT NOME,IDADE, MONTHS_BETWEEN(SYSDATE,DATA_DE_NASCIMENTO)/12 FROM TABELA_DE_CLIENTES;

SELECT ADD_MONTHS(SYSDATE,10) FROM DUAL;

SELECT SYSDATE AS HOJE, NEXT_DAY(SYSDATE,'FRIDAY') AS SEXTA FROM DUAL;

SELECT SYSDATE, LAST_DAY(SYSDATE) FROM  DUAL;

---------------------------------------------

-- FUNÇÕES DE NUMEROS

SELECT 3.4 FROM DUAL;

SELECT ROUND(3.4) FROM DUAL;

SELECT ROUND(3.5) FROM DUAL;

SELECT ROUND(3.6) FROM DUAL;

SELECT TRUNC(3.4) FROM DUAL;

SELECT TRUNC(3.5) FROM DUAL;

SELECT TRUNC(3.6) FROM DUAL;

SELECT CEIL(3.4) FROM DUAL;

SELECT CEIL(3.5) FROM DUAL;

SELECT CEIL(3.6) FROM DUAL;

SELECT FLOOR(3.4) FROM DUAL;

SELECT FLOOR(3.5) FROM DUAL;

SELECT FLOOR(3.6) FROM DUAL;

SELECT POWER(34,4) FROM DUAL;

SELECT EXP(4) FROM DUAL;

SELECT SQRT(144) FROM DUAL;

SELECT ABS(-10) FROM DUAL;

SELECT MOD(10,6) FROM DUAL;
