-- PASSAGEM DE PARAMETRO POR VALOR'IN' E POR REFERENCIA'OUT' NO PL/SQL 


-- CRIAÇÃO DA PROCEDURE DE FORMATAÇÃO DE CNPJ 
CREATE OR REPLACE PROCEDURE FORMATA_CNPJ 
( p_CNPJ IN CLIENTE.CNPJ%TYPE, p_CNPJ_SAIDA OUT CLIENTE.CNPJ%TYPE)-- PASSANDO OS PARAMENTROS p_CNPJ COM IN E p_CNPJ_SAIDA COM OUT
IS
BEGIN
  p_CNPJ_SAIDA := SUBSTR(p_CNPJ,1,3)||'/'||SUBSTR(p_CNPJ,4,2)||'-'||SUBSTR(p_CNPJ,6);
END;


-- CRIANDO UM SCRIPT PARA UTILIZAR A PROCEDURE
 SET SERVEROUTPUT ON
DECLARE
    v_CNPJ CLIENTE.CNPJ%TYPE;
    v_CNPJ_SAIDA CLIENTE.CNPJ%TYPE;
BEGIN
     v_CNPJ := '1234567890';
     v_CNPJ_SAIDA := '1234567890';
     dbms_output.put_line(v_CNPJ ||'      ' || v_CNPJ_SAIDA);
     FORMATA_CNPJ(v_CNPJ,v_CNPJ_SAIDA ); -- ENTRANDO COM OS PARAMETROS NA DIREITA COM IN E NA ESQUERDA USANDO OUT
     dbms_output.put_line(v_CNPJ ||'      ' || v_CNPJ_SAIDA); -- VALORES FORMATADOS
END;

-- UTILIZANDO O IN OUT EM UM UNICO PARAMETRO

CREATE OR REPLACE PROCEDURE FORMATA_CNPJ_SIMPLES 
(p_CNPJ IN OUT CLIENTE.CNPJ%TYPE)-- O PARAMETRO p_CNPJ PODE TANTO RECEBER DADOS COMO ATRIBUIR NESTE FORMATO
IS
BEGIN
   p_CNPJ := SUBSTR(p_CNPJ,1,3)||'/'||SUBSTR(p_CNPJ,4,2)||'-'||SUBSTR(p_CNPJ,6);
END;
-- REALIZANDO INVOCAÇÃO DA PROCEDURE
SET SERVEROUTPUT ON
DECLARE
V_CNPJ  CLIENTE.CNPJ%TYPE;
BEGIN
   V_CNPJ := '1234567890';
   FORMATA_CNPJ_SIMPLES(V_CNPJ);
   dbms_output.put_line(V_CNPJ);
END;

